/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Clases.Conectar;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import javax.swing.JTable;
import static javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE;


/**
 *
 * @author USUARIO
 */
public class Gestionar_alumnos extends javax.swing.JFrame {
    
    public static int idalumno=0;
    DefaultTableModel model= new DefaultTableModel();
    int idcurso=0;
    String nombrecurso="";
    
    /**
     * Creates new form Gestionar_alumnos
     */
    public Gestionar_alumnos() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        
        //idcurso = Gestion_cursos.idcurso;
        nombrecurso = Gestion_cursos.nombrecurso;
        //cerrar();
        
        try {
            
            Connection cn2=con.conexion();
            PreparedStatement ps=cn2.prepareStatement("SELECT * FROM alumnos WHERE id_curso_asignado= '"+nombrecurso+"'");
                
            ResultSet rs=ps.executeQuery();
            
            if(rs.next()){
                    
                    setTitle("Alumnos registrados en: "+rs.getString("id_curso_asignado"));
                    lblalumnreg.setText("Alumnos registrados en: "+rs.getString("id_curso_asignado"));
                }
        } catch (Exception e) {
            System.err.println(e);
            JOptionPane.showMessageDialog(null,"Error al cargar titulo");
        }
        
        try {
             
             PreparedStatement ps=cn.prepareStatement("SELECT * FROM alumnos WHERE id_curso_asignado= '"+nombrecurso+"'");
             ResultSet rs=ps.executeQuery();
             
             tabla_gestion_alumnos=new JTable(model);
             jScrollPane1.setViewportView(tabla_gestion_alumnos);
             
             model.addColumn("Id");
             model.addColumn("Nombre");
             model.addColumn("Apellido");
             model.addColumn("Ciclo");
             model.addColumn("Telefono");
             
             while(rs.next()){
                 
                 Object[] fila=new Object[5];
                 for (int i = 0; i < 5; i++) {
                     fila[i]=rs.getObject(i+1);
                     
                 }
                 model.addRow(fila);
             }
             
             cn.close(); 
                
            }  
         catch (SQLException e) {
            System.err.println(e);
            JOptionPane.showMessageDialog(null,"Error en el llenado de tabla");
        }
        
        ////////////////////////////////////////////////////////////////////////
        
        tabla_gestion_alumnos.addMouseListener(new MouseAdapter(){
            @Override
            public void mouseClicked(MouseEvent e){
                
                int fila_point=tabla_gestion_alumnos.rowAtPoint(e.getPoint());
                int columna_point=0;
                
                if(fila_point>-1){
                    
                    idalumno=(int)model.getValueAt(fila_point,columna_point);
                    Informacion_alumnos informacion_alumnos=new Informacion_alumnos();
                    informacion_alumnos.setVisible(true);
                    dispose();
                    
                }
                
            }
        });
        
        
        
}  
   public void cerrar(){
        
        try {
                this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
                addWindowListener(new WindowAdapter(){
                    
                    public void windowClosing(WindowEvent e){
                        
                        confirmarsalida();
                        
                    }
                    
                });
            
            
        } catch (Exception e) {
        }
        
    }
    public void confirmarsalida(){
        int valor=JOptionPane.showConfirmDialog
        (this,"¿Desea cerrar la aplicacion?","Advertencia",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
        if(valor==JOptionPane.YES_OPTION){
            
            JOptionPane.showMessageDialog(null,"Hasta Pronto","",JOptionPane.INFORMATION_MESSAGE);
            System.exit(0);
        }
        
    }     
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblalumnreg = new javax.swing.JLabel();
        btnvolver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_gestion_alumnos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblalumnreg.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        lblalumnreg.setText("Alumnos registrados en: ");

        btnvolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/8200192_previous_back_arrow_left_arrows_icon.png"))); // NOI18N
        btnvolver.setText("Volver");
        btnvolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvolverActionPerformed(evt);
            }
        });

        tabla_gestion_alumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabla_gestion_alumnos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblalumnreg)
                            .addComponent(btnvolver))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lblalumnreg)
                .addGap(28, 28, 28)
                .addComponent(btnvolver)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvolverActionPerformed
        Gestion_cursos gestion_cursos=new Gestion_cursos();
        gestion_cursos.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnvolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gestionar_alumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gestionar_alumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gestionar_alumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gestionar_alumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gestionar_alumnos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnvolver;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblalumnreg;
    private javax.swing.JTable tabla_gestion_alumnos;
    // End of variables declaration//GEN-END:variables

    Conectar con=new Conectar();
    Connection cn=con.conexion();

}

